from __future__ import annotations

import os
import select
import json
import struct
import sys
import termios
import tty
from collections import deque
from contextlib import AbstractContextManager
from pathlib import Path
from typing import Protocol

from .types import InputEvent


class EventSource(Protocol):
    def poll(self) -> InputEvent | None: ...


KEYMAP = {
    " ": InputEvent.TAKEOVER_OR_HAND_BACK,
    "s": InputEvent.SUCCESS,
    "f": InputEvent.FAILURE,
    "r": InputEvent.RESUME_AUTO,
    "q": InputEvent.QUIT,
    "\x1b": InputEvent.QUIT,
}


class KeyboardEventSource(AbstractContextManager):
    """Non-blocking terminal keys. A USB pedal mapped to Space works unchanged."""

    def __init__(self, stream=None):
        self.stream = stream or sys.stdin
        self._previous = None

    def __enter__(self):
        if not self.stream.isatty():
            raise RuntimeError("keyboard takeover requires an interactive TTY")
        self._previous = termios.tcgetattr(self.stream.fileno())
        tty.setcbreak(self.stream.fileno())
        return self

    def poll(self) -> InputEvent | None:
        ready, _, _ = select.select([self.stream], [], [], 0)
        if not ready:
            return None
        return KEYMAP.get(os.read(self.stream.fileno(), 1).decode(errors="ignore"))

    def __exit__(self, exc_type, exc, tb):
        if self._previous is not None:
            termios.tcsetattr(self.stream.fileno(), termios.TCSADRAIN, self._previous)
        return False


class QueueEventSource:
    """Test/button adapter: enqueue logical events from any external device."""

    def __init__(self):
        self.events = deque()

    def put(self, event: InputEvent) -> None:
        self.events.append(event)

    def poll(self) -> InputEvent | None:
        return self.events.popleft() if self.events else None


INPUT_EVENT_STRUCT = struct.Struct("@llHHi")
EV_KEY = 0x01
KEY_DOWN = 1


class LinuxTwoButtonEventSource(AbstractContextManager):
    """Read two physical buttons directly from a Linux evdev device.

    The JSON file is generated by ``tools/identify_two_key_keyboard.py``.
    Direct evdev input does not depend on terminal focus and ignores key repeat.
    """

    def __init__(self, config_path: str | Path):
        config = json.loads(Path(config_path).read_text())
        self.device = str(config["device"])
        buttons = config["buttons"]
        self.keymap = {
            int(buttons["align"]["code"]): InputEvent.ALIGN_LEADER,
            int(buttons["release"]["code"]): InputEvent.RELEASE_LEADER,
        }
        if len(self.keymap) != 2:
            raise ValueError("align and release must use two different key codes")
        self._fd: int | None = None
        self._buffer = bytearray()
        self._events = deque()

    def __enter__(self):
        self._fd = os.open(self.device, os.O_RDONLY | os.O_NONBLOCK)
        return self

    def poll(self) -> InputEvent | None:
        if self._events:
            return self._events.popleft()
        if self._fd is None:
            raise RuntimeError("button event source is not open")
        while True:
            try:
                chunk = os.read(self._fd, INPUT_EVENT_STRUCT.size * 32)
            except BlockingIOError:
                break
            if not chunk:
                raise RuntimeError(f"button device disconnected: {self.device}")
            self._buffer.extend(chunk)
        while len(self._buffer) >= INPUT_EVENT_STRUCT.size:
            raw = self._buffer[: INPUT_EVENT_STRUCT.size]
            del self._buffer[: INPUT_EVENT_STRUCT.size]
            _sec, _usec, event_type, code, value = INPUT_EVENT_STRUCT.unpack(raw)
            if event_type == EV_KEY and value == KEY_DOWN and code in self.keymap:
                self._events.append(self.keymap[code])
        return self._events.popleft() if self._events else None

    def __exit__(self, exc_type, exc, tb):
        if self._fd is not None:
            os.close(self._fd)
            self._fd = None
        return False


class CompositeEventSource(AbstractContextManager):
    """Poll several input sources while preserving their context cleanup."""

    def __init__(self, *sources):
        self.sources = sources
        self._entered = []

    def __enter__(self):
        try:
            for source in self.sources:
                self._entered.append(source.__enter__())
        except BaseException:
            self.__exit__(*sys.exc_info())
            raise
        return self

    def poll(self) -> InputEvent | None:
        for source in self._entered:
            event = source.poll()
            if event is not None:
                return event
        return None

    def __exit__(self, exc_type, exc, tb):
        suppress = False
        for source in reversed(self._entered):
            suppress = source.__exit__(exc_type, exc, tb) or suppress
        self._entered.clear()
        return suppress
